---
title: "10_1"
author: "Gorbarenko Artem"
date: "27 12 2020"
output: html_document
---


Загрузка библиотек
```{r}
library(sf)
library(tmap)
library(readxl)
library(raster)
library(tibble)
library(mapview)
library(eurostat)
library(classInt)
library(gapminder)
library(tidyverse)
library(googlesheets)
library(rnaturalearth)
```
Карта №1«Климатические пояса» Задание входных данных и перепроецирование

```{r}
```


```{r}
rivers = ne_download(scale = 110, 
                     type = 'rivers_lake_centerlines', 
                     category = 'physical') %>% 
  st_as_sf() 

lakes = ne_download(scale = 110, 
                    type = 'lakes', 
                    category = 'physical') %>% 
  st_as_sf()

ocean = ne_download(scale = 110, 
                    type = 'ocean', 
                    category = 'physical') %>% 
  st_as_sf() 

geographic_lines = ne_download(scale = 110, 
                               type = 'geographic_lines', 
                               category = 'physical')%>% 
  st_as_sf() 

climate = st_read('climates.gpkg') 

mapview(rivers) +  mapview(lakes) + mapview(ocean) + mapview(geographic_lines)


```

```{r}
climate$Type = ordered(climate$Type, levels = c('Арктический', 'Субарктический', 'Умеренный', 'Субтропический', 'Тропический', 'Субэкваториальный', 'Экваториальный')) #для упорядочения названий
climate = climate %>% 
  arrange(Type)

maps = lst( ocean, rivers, lakes, geographic_lines, climate)   # создание списка для возможности общего трансформирования
maps_w = lapply(maps, st_transform, crs = "+proj=wag5")  # псевдоцилиндрическая проекция Вагнера
geolin = geographic_lines %>% 
  filter(stringr::str_detect(geographic_lines$name_ru, 'Южный тропик|Северный тропик|
                             Северный полярный круг|Южный полярный круг')) # для подписей линий
```



Визуализация карты
```{r}
col1 = c('#6600CC', '#0066CC', '#339999', '#FFFF99', '#FF6633', '#FF6666', '#FF3333') # цвета климатических поясов

tm_shape(maps_w$ocean) +
  tm_fill(col = 'grey') +
  tm_borders(col = 'grey') +
tm_shape(maps_w$rivers) +
  tm_lines(col = 'grey') +
tm_shape(maps_w$lakes) +
  tm_fill(col = 'grey') +
  tm_borders(col = 'grey') +
tm_shape(maps_w$geographic_lines) +
  tm_lines(col = '#5f5f5f', lty = 2, lwd = 0.1) +
tm_shape(maps_w$climate) +
  tm_polygons('Type', palette = col1, alpha = 0.5, title = '') +
tm_layout(legend.position = c('left', 'bottom'),
            fontfamily = 'OpenSans',
            main.title.size = 1,
            main.title = 'Климатические пояса',
            main.title.position = 'center',
            frame = FALSE,
            legend.frame = FALSE,
            legend.text.size = 1,
            legend.hist.size = 1,
            outer.margins = c(0.1, 0.1, 0.1, 0.1),
            inner.margins = c(0, 0, 0, 0)) +
tm_grid(x = seq(-180, 180, by = 30),
          y = seq(-90, 90, by = 30),
          lwd = 0.2,
          col = '#5f5f5f',
          projection = 4326,
          labels.inside.frame = FALSE,
          labels.format = list(fun = function(X) paste0(X, '°')))
```